# Generated by Django 4.2.2 on 2024-01-22 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp2', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasks',
            name='date',
            field=models.DateField(default='1990-3-6'),
            preserve_default=False,
        ),
    ]
